---
layout: cv
title: Spencer Keller's CV
---
# Spencer Keller
Tax associate, entrepeneur, follower of Christ.

<div id="webaddress">
| <a href="https://www.linkedin.com/in/spencer-keller12/">My linkedin page</a>
<!-- | <a href="https://yourusername.github.io/datascience_portfolio/gh-pages/resume.pdf">Download PDF</a> -->
| <a href="https://github.com/byuidatascience/datascience_portfolio/blob/gh-pages/resume.pdf">Download PDF</a>
</div>


## Currently

I am currently an intern at Smith Kunz & Associates, where I assist with the preparation of both personal and business tax returns. In this role, I work with financial documents, organize client information, and support the tax team in ensuring accurate and timely filings. This experience has strengthened my understanding of tax regulations, attention to detail, and ability to handle sensitive financial data in a professional environment.

## Specialized in


Private client tax services, individual and business tax return preparation, and business entity selection for tax optimization. Experience with partnership taxation, including K-1 analysis, and exposure to state and local tax (SALT) compliance and multistate apportionment. Skilled in identifying tax credits and deductions, financial data analysis, and ensuring compliance with federal and state regulations. Strong focus on accuracy, efficiency, and handling sensitive financial information.

## Education

Expected April 2026
Brigham Young University – Idaho, Rexburg, Idaho

Bachelor of Science in Accounting (GPA: 3.42)
Cluster in Data Science


## Experience


January 2026 – Present
Smith Kunz & Associates, Rexburg, ID

Prepared and filed 50+ federal and state individual and business tax returns
Utilized TaxDome and UltraTax to streamline workflows and identify deductions and credits

June 2025 – August 2025
Andersen, Los Angeles, CA

Prepared and reviewed partnership K-1s, analyzing income, deductions, and credits
Supported state and local tax (SALT) engagements, including multistate compliance and tax research

April 2023 – December 2024
Ecoshield Pest Solutions, Nashville, TN

Generated $280K in personal revenue through consultative sales
Managed and mentored a sales team producing $500K+ in revenue
Led training sessions focused on communication, objection handling, and closing strategies

## Leadership


October 2023 – Present
BYU-Idaho Club Volleyball
Team Captain; led team to Mountain West Championship
Earned All–Mountain West First Team honors

August 2020 – September 2022
The Church of Jesus Christ of Latter-day Saints, Florianópolis, Brazil

Trained and supported 150 missionaries across 30 cities
Provided mentorship, leadership, and performance feedback in diverse environments


## Technical Skills

Programming in VBA, SQL, Python, and RStudio, with experience applying data analysis techniques. Fluent in Portuguese, conversational in Spanish, and native in English.



<!-- ### Footer

Last updated: May 2013 -->